### ISSUE TITLE
Status icon is not available. 

### ISSUE THREAD

**Issue by dintsin010** [kkamkou/chrome-jironimo#156]
we are using standalone version of 
Atlassian JIRA Project Management Software (v7.2.4#72006-sha1:91606a8) 
Chrome 54.0.2840.100 (64-bit)
Ubuntu 16 & Windows 8

http://prntscr.com/ddkrf9 Here it is :(

looking deeper  http://prntscr.com/ddktpk

**Comment by kkamkou** [comment]
What is the real url of the icon(in a ticket)? Could you copy-paste it here? This information comes from the ticket data, the extension does nothing.

**Comment by dintsin010** [comment]
The problem emerges on "To Do" status
ng-src="http://jira.oki-toki.net:8080/"

Others are looking good:
ng-src="http://jira.oki-toki.net:8080/images/icons/statuses/open.png"
http://jira.oki-toki.net:8080/images/icons/statuses/inprogress.png

2016-11-30 20:02 GMT+02:00 Kanstantsin Kamkou <notifications@github.com>:

**Comment by kkamkou** [comment]
Ok. Thank you. I have the same on the local installation. Should be fixed in a new release.

**Comment by dintsin010** [comment]
:) Thank you

2016-12-03 16:30 GMT+02:00 Kanstantsin Kamkou <notifications@github.com>:
