### ISSUE TITLE
Set the default hotkey for the extension

### ISSUE THREAD

**Issue by kkamkou** [kkamkou/chrome-jironimo#98]
It'll be nice if we can set the default hotkey for the extension.

**Comment by kkamkou** [comment]
@Arany what do you think about the hotkey combination? The commit 9c57cfe30af50131d7043c25769f9c9b47250121 sets `Ctrl + J`. Any preferences?

**Comment by Arany** [comment]
@kkamkou You mean to open the extension popup? Ctrl + J sounds good. But it should be Cmd + J on mac I guess.

**Comment by kkamkou** [comment]
@Arany oopps, it is `Alt+J`, because `Ctrl+J` is downloads
